api_platform:
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api'
    patch_formats:
        json: ['application/merge-patch+json']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
    swagger:
        versions: [3]
        api_keys:
            apiJWTLogin:
                name: BEARER
                type: header
